/*
 * Copyright 2024 Stanislav Mikhailov (xavetar)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */

use super::{
    week::{
        REPEAT_WEAK_DAY_CYCLE,
        SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN,
        SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN,
        SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR
    },
    months::{
        MONTHS_IN_YEAR,
        BASE_MONTH_DAYS, LEAP_MONTH_DAYS
    }
};


pub const JULIAN_BASE_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const JULIAN_LEAP_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16 + LEAP_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const GREGORIAN_BASE_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const GREGORIAN_LEAP_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16 + LEAP_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const SOLAR_BASE_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + BASE_MONTH_DAYS[1] as u16 + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const SOLAR_LEAP_XAVETAR: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + LEAP_MONTH_DAYS[0] as u16 + LEAP_MONTH_DAYS[1] as u16 + LEAP_MONTH_DAYS[2] as u16 + LEAP_MONTH_DAYS[3] as u16 + LEAP_MONTH_DAYS[4] as u16 + LEAP_MONTH_DAYS[5] as u16 + LEAP_MONTH_DAYS[6] as u16 + LEAP_MONTH_DAYS[7] as u16 + LEAP_MONTH_DAYS[8] as u16 + LEAP_MONTH_DAYS[9] as u16 + LEAP_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const JULIAN_BASE_SAKAMOTO: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1)) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_JULIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const GREGORIAN_BASE_SAKAMOTO: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1)) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_GREGORIAN as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];

pub const SOLAR_BASE_SAKAMOTO: [u8; MONTHS_IN_YEAR as usize] = [
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1)) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8,
    ((SHIFT_BEFORE_FIRST_PRESENTATION_WEEK_DAY_SOLAR as u16 + BASE_MONTH_DAYS[0] as u16 + ((BASE_MONTH_DAYS[1] as u16) - 1) + BASE_MONTH_DAYS[2] as u16 + BASE_MONTH_DAYS[3] as u16 + BASE_MONTH_DAYS[4] as u16 + BASE_MONTH_DAYS[5] as u16 + BASE_MONTH_DAYS[6] as u16 + BASE_MONTH_DAYS[7] as u16 + BASE_MONTH_DAYS[8] as u16 + BASE_MONTH_DAYS[9] as u16 + BASE_MONTH_DAYS[10] as u16) % REPEAT_WEAK_DAY_CYCLE as u16) as u8
];